PcelarstvoApp/Pcelarstvo/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Pcelarstvo.Areas.HelpPage.Models;

namespace Pcelarstvo.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

PcelarstvoApp/Pcelarstvo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <div id="userSettings">
        @Html.Partial("_UserSettings")
    </div>

    <div id="body">
        @RenderBody()
    </div>

    <footer>
        <nav>
            <ul id="menu">
                <li>@Html.ActionLink("Todo List", "Index", "Home", new { area = "" }, null)</li>
                <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
            </ul>
        </nav> 
        <p>Learn more about <a href="http://go.microsoft.com/fwlink/?LinkId=273732">Single Page Applications</a></p>
        <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/ajaxlogin")
    @RenderSection("scripts", required: false)
</body>
</html>

PcelarstvoApp/Pcelarstvo/Views/Shared/_UserSettings.cshtml
@if (Request.IsAuthenticated) {
    <text>
        Hello, @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "username", title = "Manage" })
        @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" })) {
            @Html.AntiForgeryToken()
            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
        }
    </text>
}